name: '532'
channels:
  - conda-forge
dependencies:
  - numpy
  - plotly
  - matplotlib
  - pandas
  - python
  - ipykernel
  - seaborn
  - scienceplots
  - scikit-learn
  - nbformat
  - shiny
prefix: /Users/harry/miniforge3/envs/532
